apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.app.name }}
  namespace: {{.Release.Namespace}}
spec:
  host: {{ .Values.app.name }}
  subsets:
    - name: subset-v1
      labels:
        version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}
  namespace: {{.Release.Namespace}}
spec:
  hosts:
    - {{ .Values.app.name }}
  http:
    - route:
        - destination:
            host: {{ .Values.app.name }}
            subset: subset-v1
