apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: {{ .Values.app.name }}
      port: {{ .Values.app.service.port }}
      targetPort: 3000