apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}-{{ .Values.vs.subset }}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: {{ .Values.app.name }}-{{ .Values.vs.subset }}
    version: {{ .Values.vs.subset }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: 3000