apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}-vs
  namespace: {{.Release.Namespace}}
spec:
  gateways:
    - {{ .Values.vs.gateway }}
  hosts:
    - {{ .Values.vs.host }}
  http:
    - route:
        - destination:
            host: {{ .Values.app.name }}-svc-{{ .Values.app.version }}
            subset: {{ .Values.vs.subset }}