apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.version }}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ .Values.app.name }}
    service: {{ .Values.app.name }}
    version: {{ .Values.app.version }}
spec:
  selector:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.version }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: 3000