apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}
  namespace: default
spec:
  gateways:
    - {{ .Values.vs.gateway }}
  hosts:
    - {{ .Values.app.service.name }}
  http:
    - route:
        - destination:
            host: {{ .Values.app.service.name }}-{{ .Values.vs.subset }}.{{.Release.Namespace}}.svc.cluster.local
            subset: {{ .Values.vs.subset }}