apiVersion: v1
kind: ServiceAccount
metadata:
  name: invoice-mgr-data-sa
  namespace: {{.Release.Namespace}}
  labels:
    account: invoice-mgr-data
    app: invoice-mgr-data
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-data
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-mgr-data
  template:
    metadata:
      labels:
        app: invoice-mgr-data
        version: 1.0.0
    spec:
      serviceAccountName: invoice-mgr-data-sa
      containers:
        - name: invoice-mgr-data
          image: invoice-mgr-data:v1.0.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Never
          env:
            - name: SPACE
              value: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-mgr-data-svc
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: invoice-mgr-data
  ports:
    - name: http-invoice-mgr-data
      port: 3300
      targetPort: 3000
