apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-v1
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: v1
    spec:
      serviceAccountName: invoice-mgr-sa
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.container.image }}
          command: [ "npm" ]
          args: [ "run", {{ .Values.app.exec }} ]
          ports:
            - containerPort: 3000
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: GENERATOR_URL
              value: {{ .Values.GENERATOR_URL }}
            - name: DATA_URL
              value: {{ .Values.DATA_URL }}
            - name: PAYMENT_URL
              value: {{ .Values.PAYMENT_URL }}
            - name: SPACE
              value: {{ .Release.Namespace }}
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            successThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
