apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: invoice-mgr-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: invoice-mgr-virtual-service
spec:
  hosts:
    - "*"
  gateways:
    - invoice-mgr-gateway
  http:
  - route:
    - destination:
        host: invoice-mgr-app-svc
        port:
          number: 3000