apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: generator-dest-rule
  namespace: default
spec:
  host: generator
  subsets:
    - name: generator-subset-v1
      labels:
        version: v1
    - name: generator-subset-v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: generator-vs
spec:
  hosts:
    - generator
  http:
    - name: generator-v1
      route:
        - destination:
            host: generator
            subset: generator-subset-v1
    - name: generator-v2
      route:
        - destination:
            host: generator
            subset: generator-subset-v2