apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: generator-dest-rule
  namespace: default
spec:
  host: generator
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: generator-subset-v1
      labels:
        version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: generator-vs
spec:
  hosts:
    - generator
  http:
    - name: generator
      route:
        - destination:
            host: generator
            subset: generator-subset-v1