apiVersion: v1
kind: Service
metadata:
  name: generator
  namespace: default
  labels:
    app: generator
    version: v1
spec:
  selector:
    app: generator
    version: v1
  ports:
    - name: http
      port: 3100
      targetPort: 3000
