apiVersion: v1
kind: Service
metadata:
  name: generator-v1
  namespace: default
  labels:
    app: generator
    version: v1
spec:
  selector:
    app: generator
    version: v1
  ports:
    - name: http
      port: 3100
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: generator-v2
  namespace: default
  labels:
    app: generator
    version: v2
spec:
  selector:
    app: generator
    version: v2
  ports:
    - name: http
      port: 3100
      targetPort: 3000
