apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v1
  template:
    metadata:
      labels:
        app: payment
        version: v1
    spec:
      serviceAccountName: invoice-mgr-sa
      containers:
        - name: payment
          image: x00159358/invoice-mgr:v1.0.0
          command: [ "npm" ]
          args: [ "run", "payment" ]
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: GENERATOR_URL
              value: http://generator:3100
            - name: DATA_URL
              value: http://data:3300
            - name: PAYMENT_URL
              value: http://payment:3200
            - name: SPACE
              value: default
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            successThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5