apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: payment-dest-rule
  namespace: default
spec:
  host: payment
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: payment-subset-v1
      labels:
        version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: payment-vs
spec:
  hosts:
    - payment
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  http:
    - route:
        - destination:
            host: payment
            subset: payment-subset-v1