apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: default
  labels:
    app: payment
spec:
  selector:
    app: payment
  ports:
    - name: http
      port: 3200
      targetPort: 3000
